### PR TITLE
Small compilation error

### PR DESCRIPTION
**Pull request by nagashayan**
“=“ (equals) sign was missing while declaring constant so was not able
to include header file.

### CODE REVIEW

**Comment by nagashayan** [comment]
@Forceflow Thanks this was my first pull request 👍

**Comment by Forceflow** [comment]
Cool! Thanks. 

Next time, try not to add too much extra tabs/spaces to a file - it is frowned upon :)

**Comment by nagashayan** [comment]
sure :) its because of my auto beautify plugin in atom.

**Comment by nagashayan** [comment]
@Forceflow any example for using this library am not able to decode the value. 

Am trying to decode like this,
morton2D_32_decode(morton, lat, lng) where morton, lng is uint_fast32_t and lat is uint_fast16_t

am getting this error 
error: no matching function
      for call to 'm2D_d_sLUT'
what const the first argument should be? 

any example would be appreciated.

**Comment by Forceflow** [comment]
Your morton input should be a 32-bit value and your two coordinate outputs (lat, long) should be 16-bit values there.

**Pull request merged**
